### ISSUE TITLE
Officialness of fork?

### ISSUE THREAD

**Issue by xloem** [recordmydesktop/recordmydesktop#1]
How semi-official is your fork?

The original software is kind of a dead end for visitors, and is still a recommended solution in some areas for the problem of desktop video.

If we added comments on stale issue threads etc leading to this fork, people would find it, and it could be a successor.  What do you think?

note to self: next time just use this energy to add the proposed links, and let the interested people work together to sort out where to land.  works better if you forget it later.

**Comment by vcaputo** [comment]
Well, it's a case of scratching my own itch, but at this point I suspect this fork is probably the most usable incarnation of the tool.

There are still some issues to address, and no doubt I've introduced some new ones, but at least for my use cases this fork is mostly usable which is a lot more than I can say for the previous state.

I approached the debian package maintainer earlier in the fork about adopting the fork, but it sounded like they were more interested in simply dropping the package at the time.

**Comment by vcaputo** [comment]
BTW, in case it wasn't clear, I'm fine with linking this fork from stale issues, though I can't make any promises about responding to reported issues in a timely fashion.

It is at least the primary X recording tool I'm using for now, so it sees *some* love.  But I'm also beginning to explore porting my window manager to Wayland, which once completed, will presumably deprecate my use of this tool.. unless adding wayland support to recordMyDesktop makes sense in that scenario.

**Comment by xloem** [comment]
When I had trouble making this work, I ended up using obs (open broadcasting studio), which works pretty well.  It takes some basic commandline arguments to initiate recording on launch, but it doesn't have a way to disable the gui.  I hacked it a little to change the provided resolutions around gpu encoding.

**Comment by vcaputo** [comment]
Yeah OBS is popular and should work well considering how much more attention it receives, I don't blame you there.

I prefer how rmd is more CLI-oriented and can defer actual encoding until after the recording is finished, it's convenient for WM integration and can play nicer with slower systems.

But the code is still an absolute disaster, thanks for your interest and the bug reports in any case.

**Comment by xloem** [comment]
A post on sourceforge indicates the original maintainer is actively working on this at https://github.com/Enselic/recordmydesktop

**Comment by vcaputo** [comment]
I've created a github org where we could collaborate on moving this project forward into the future, hopefully things can converge there with interested and capable parties as members.

https://github.com/recordmydesktop

**Comment by xloem** [comment]
Enselic said on sourceforge that they reached out to you via email.

**Comment by bl-ue** [comment]
@vcaputo any news regarding this?  cc @Enselic

As a maintainer of [tldr-pages](https://github.com/tldr-pages), I'd like to write a [tldr](https://github.com/tldr-pages/tldr) page for this app and I want to know which one study.

**Comment by Enselic** [comment]
@bl-ue Current status is that I am trying to reach out to the Debian package maintainer to get my [0.4.0](https://github.com/Enselic/recordmydesktop/releases/tag/v0.4.0) release included in Debian, but I have not managed to get in touch with him so far. If the maintainer is Missing In Action, that process can take many more months.

My 0.4.0 release is included in the upcoming Ubuntu release however, see https://launchpad.net/ubuntu/+source/recordmydesktop/0.4.0-0ubuntu1

Me and @vcaputo had some email correspondence, which I greatly appreciated, but so far we did not agree on the path forward for the project. So this fork is not an official fork.

**Comment by bl-ue** [comment]
Okay, thank you.  I've been looking at the latest release—it's history is interesting!

On another note @Enselic, which is the correct version of the command name: `recordMyDesktop` or `recordmydesktop`?
