### ISSUE TITLE
 X Error: BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by llzz9595** [recordmydesktop/recordmydesktop#6]
when i run record:

 X Error: BadMatch (invalid parameter attributes)

**Comment by vcaputo** [comment]
Using what version of recordMyDesktop?  Is this from a distro-provided build or did you build it yourself from git master?

Also try running under `xtrace` to see more specifically which X call failed.

**Comment by vcaputo** [comment]
@llzz9595 ping?

**Comment by vcaputo** [comment]
Closing this as it's not actionable as-is and no response.
