### ISSUE TITLE
--use-jack arg parsing is broken

### ISSUE THREAD

**Issue by TatriX** [recordmydesktop/recordmydesktop#8]
Hi!

I was trying to debug why `--use-jack` ignores the second port and ended up in this repo.

The following invocation of 460b6f4 (in dwm if that matters)
```
./recordmydesktop --windowid=0x1400469 --fps=60 --use-jack SuperCollider:out_1 SuperCollider:out_2
```
gives me an error:
```
Specified Area is larger than window!
```
or sometimes 
```
-x must not be less than 0.
```

Version from Arch repo [0.4.0-2](https://github.com/Enselic/recordmydesktop) works fine with `--windowid`.

**Comment by TatriX** [comment]
```
rrect.width = 35748
winrect.width = 1092
rrect.height = 44481
args.y = 21909
winrect.height = 854
Specified Area is larger than window!
```

It seems that `y` of `ProgArgs *args` in `rmdSetBRWindow` uninitialized.

edit: first invocation of `while ((arg_id = poptGetNextOpt(popt_context)) > 0) {` seems to corrupt `y` value.

**Comment by TatriX** [comment]
It seems https://github.com/recordmydesktop/recordmydesktop/blob/master/src/rmd_parseargs.c#L195 is responsible for both memory corruption and broken use-jack as it uses `arg_return->x` instead of `NULL`.

edit: See https://github.com/Enselic/recordmydesktop/commit/8774cada07aa04f9d0260b624ce26081ede5e05c

**Comment by TatriX** [comment]
I'm not sure that popt supports parsing of multiple string args in a way the current code is written.
Here's a quick patch that uses comma as a separator within a single string:
```
./recordmydesktop  --use-jack "SuperCollider:out_1,SuperCollider:out_2"
```

```
diff --git a/src/rmd_parseargs.c b/src/rmd_parseargs.c
index fcf73af..0f036b9 100644
--- a/src/rmd_parseargs.c
+++ b/src/rmd_parseargs.c
@@ -192,7 +192,7 @@ boolean rmdParseArgs(int argc, char **argv, ProgArgs *arg_return)
                  "SOUND_DEVICE" },

                { "use-jack", '\0',
-                 POPT_ARG_STRING | RMD_USE_JACK_EXTRA_FLAG, &arg_return->x, RMD_ARG_USE_JACK,
+                 POPT_ARG_ARGV | RMD_USE_JACK_EXTRA_FLAG, NULL, RMD_ARG_USE_JACK,
                  "Record audio from the specified list of space-separated jack ports.",
                  "port1 port2... portn" },

@@ -357,15 +357,18 @@ boolean rmdParseArgs(int argc, char **argv, ProgArgs *arg_return)
                        {
                                arg_return->jack_nports = 0;

-                               while (arg) {
-
-                                       arg_return->jack_nports++;
-
-                                       arg_return->jack_port_names[arg_return->jack_nports - 1] = malloc(strlen(arg) + 1);
-                                       strcpy(arg_return->jack_port_names[arg_return->jack_nports - 1], arg);
-
-                                       arg = poptGetOptArg(popt_context);
-                               }
+                                // split arg by "," to get port names
+                                int ports_len = strlen(arg);
+                                int start_index = 0;
+                                for (int index = 0; index < ports_len + 1; index++) {
+                                    // TODO: comma  may clash with some port names?
+                                    // Make it configurable or use better parsing strategy.
+                                    if (arg[index] == ',' || arg[index] == '\0') {
+                                        int port_len = index - start_index;
+                                        arg_return->jack_port_names[arg_return->jack_nports++] = strndup(arg + start_index, port_len);
+                                        start_index = index + 1;
+                                    }
+                                }

                                if (arg_return->jack_nports > 0) {
                                        arg_return->use_jack = 1;
```

Unfortunately while this fixes ports parsing recording itself is broken:
```
Initializing...
Capturing!
^CShutting down.
*********************************************

Cached 6 MB, from 15 MB that were received.
Average cache compression ratio: 61.3 %

*********************************************
Saved 3 frames in a total of 2 requests
..
```
it stays in this state forever.

At the same time fork by @Enselic with the same patch works as expected and captures both channels.

**Comment by vcaputo** [comment]
Hey!  Thanks for the contribution here.  I'm traveling on vacation at the moment but should be able to get around to looking at this within a few weeks.

The popt return in x bug is an obvious one to fix, but the way the inherited --use-jack code is parsing those arguments also looks clearly broken based on my limited understanding of popt.  It can't have possibly ever worked.

It should be clear by now that I have never tested the jack functionality, so that stuff is still largely as-inherited from enselic/original authors at the time of forking.  But I probably introduced some new bugs in the synchronization at shutdown surrounding the jack stuff that you're seeing where it hangs at exit.  I don't experience anything like that but just use alsa over here.

If you're up for helping test and get the jack support in shape I'm happy to collaborate on tidying up that area.  This fork in my experience is *far* more usable than what I started with FWIW.

**Comment by TatriX** [comment]
Sure! I've tried to debug why it hangs, but couldn't find a way to get a backtrace when that happens yet.
Just let me know how I can help when you are back.
Have a nice rest of the vacation then!

**Comment by vcaputo** [comment]
@TatriX Dunno if you still have any use for this, but I think the JACK support is fixed in master as of now.

Apologies for taking longer than anticipated to get around to this.  I had some family matters to tend to that somewhat took over for awhile there...

**Comment by vcaputo** [comment]
> I'm not sure that popt supports parsing of multiple string args in a way the current code is written. Here's a quick patch that uses comma as a separator within a single string:
> 
> ```
> ./recordmydesktop  --use-jack "SuperCollider:out_1,SuperCollider:out_2"
> ```
> 
> ```
> diff --git a/src/rmd_parseargs.c b/src/rmd_parseargs.c
> index fcf73af..0f036b9 100644
> --- a/src/rmd_parseargs.c
> +++ b/src/rmd_parseargs.c
> @@ -192,7 +192,7 @@ boolean rmdParseArgs(int argc, char **argv, ProgArgs *arg_return)
>                   "SOUND_DEVICE" },
> 
>                 { "use-jack", '\0',
> -                 POPT_ARG_STRING | RMD_USE_JACK_EXTRA_FLAG, &arg_return->x, RMD_ARG_USE_JACK,
> +                 POPT_ARG_ARGV | RMD_USE_JACK_EXTRA_FLAG, NULL, RMD_ARG_USE_JACK,
>                   "Record audio from the specified list of space-separated jack ports.",
>                   "port1 port2... portn" },
> 
> @@ -357,15 +357,18 @@ boolean rmdParseArgs(int argc, char **argv, ProgArgs *arg_return)
>                         {
>                                 arg_return->jack_nports = 0;
> 
> -                               while (arg) {
> -
> -                                       arg_return->jack_nports++;
> -
> -                                       arg_return->jack_port_names[arg_return->jack_nports - 1] = malloc(strlen(arg) + 1);
> -                                       strcpy(arg_return->jack_port_names[arg_return->jack_nports - 1], arg);
> -
> -                                       arg = poptGetOptArg(popt_context);
> -                               }
> +                                // split arg by "," to get port names
> +                                int ports_len = strlen(arg);
> +                                int start_index = 0;
> +                                for (int index = 0; index < ports_len + 1; index++) {
> +                                    // TODO: comma  may clash with some port names?
> +                                    // Make it configurable or use better parsing strategy.
> +                                    if (arg[index] == ',' || arg[index] == '\0') {
> +                                        int port_len = index - start_index;
> +                                        arg_return->jack_port_names[arg_return->jack_nports++] = strndup(arg + start_index, port_len);
> +                                        start_index = index + 1;
> +                                    }
> +                                }
> 
>                                 if (arg_return->jack_nports > 0) {
>                                         arg_return->use_jack = 1;
> ```
> 
> Unfortunately while this fixes ports parsing recording itself is broken:


So rather than playing games parsing the ports from a single arg, I just switched it to handle `--use-jack` multiple times for adding multiple ports.  I looked at the JACK API docs/source and it didn't seem to prohibit any chars from port names, so there was no real robust way to split them in a single argument.  Multiple `--use-jack` flags seems like a reasonable alternative, plus it's far less code this way (also that kind of code tends to be bug prone in C)

**Comment by TatriX** [comment]
Thank you, I appreciate your time! I'll give it a try soon.

**edit**: works like a charm!

**Comment by vcaputo** [comment]
@TatriX sweet, thanks for verifying, and with such quickness.

Hmm I just noticed the man page doesn't even mention --use-jack.  It appears like JACK support was simply unfinished, frankly I'm surprised it's actually working.

If you don't mind, have you verified it produces properly synchronized audio-video in a long-ish recording?  I did some cursory testing here just to make sure it recorded sound with an ad-hoc jackd running (I don't normally use JACK), but can't say I verified it stays synchronized properly.  I should probably do more testing myself too.

FYI: A good trick for checking the A-V sync is to watch a movie w/sound playing while recording.  Then watch the recording and see if it's correctly synchronized for the duration...  Generating some load like compiling a kernel during the recording helps stress the sync machinery.

**Comment by TatriX** [comment]
I did a few quick tests with pulse sink and jack and sync seems to be working just fine!
```
./recordmydesktop --use-jack "PulseAudio JACK Sink:front-left" --use-jack "PulseAudio JACK Sink:front-right" --windowid=0x1800007
```
For me, the use case is to record both visualization and sound generated, so generally I try to make sure that I don't have a kernel compiling in the background while my high priority audio thread is supposed to do the synthesis :)

I'll try to do a test with SuperCollider sometime soon.
Thank you for the patch!
